{
  "headers": {
    "client_id": "wxwcecwkqklsn124",
    "client_secret": "wxwcecwkqklsn124",
    "content-type": "application/xml",
    "user-agent": "PostmanRuntime/7.28.4",
    "accept": "*/*",
    "postman-token": "4132d9ba-3142-4c2f-a6dd-5527cacd1a27",
    "host": "localhost:8081",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "content-length": "652"
  },
  "clientCertificate": null,
  "method": "POST",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/api/bookmovies",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/bookmovies",
  "listenerPath": "/api/*",
  "relativePath": "/api/bookmovies",
  "localAddress": "/127.0.0.1:8081",
  "uriParams": {},
  "rawRequestUri": "/api/bookmovies",
  "rawRequestPath": "/api/bookmovies",
  "remoteAddress": "/127.0.0.1:56403",
  "requestPath": "/api/bookmovies"
}