#%RAML 1.0 Trait

headers:
      client_id:
        type: string
        required: true
        example:
          wxwcecwkqklsn124
      client_secret:
        type: string
        required: true
        example:
          wxwcecwkqklsn124