{
  "headers": {
    "client_id": "wxwcecwkqklsn124",
    "client_secret": "wxwcecwkqklsn124",
    "content-type": "application/xml",
    "user-agent": "PostmanRuntime/7.28.4",
    "accept": "*/*",
    "postman-token": "87ac3c59-d5e1-4f02-b531-9909e7ac5c68",
    "host": "localhost:8081",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "content-length": "652"
  },
  "clientCertificate": null,
  "method": "GET",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/api/movies",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/movies",
  "listenerPath": "/api/*",
  "relativePath": "/api/movies",
  "localAddress": "/127.0.0.1:8081",
  "uriParams": {},
  "rawRequestUri": "/api/movies",
  "rawRequestPath": "/api/movies",
  "remoteAddress": "/127.0.0.1:52827",
  "requestPath": "/api/movies"
}